project:
  type: website
  output-dir: "docs"
date: today
lang: fr
language:
  title-block-author-single: "Auteur"
author:
  - name: "D<sup>r</sup> Philippe MICHEL"
    orcid: "0000-0003-2392-7186"
    email: "philippe.michel@ght-novo.fr"
    role: "Statisticien"
    affiliations:
        name: "USRC - Hôpital NOVO"
        city: Pontoise
        department: "Unité de Soutien à la Recherche Clinique"
  - name: "M<sup>me</sup> Delphine DUVAL"
    affiliations:
        name: "Hôpital NOVO"
        city: Pontoise
        department: "Service d'hématologie"
website:
  image: novo_usrc.png
  title: "HDJ-TO-Hémato"
  page-navigation: true
  search:
    location: sidebar
    type: textbox
  navbar:
    logo: novo_usrc.png
    background: primary
    search: true
    left:
      - text: "        Généralités"
        href: index.qmd
      - text: "Plan d'analyse"
        href: plan_analyse.qmd
      - text: "Rapport statistique"
        href: rapport.qmd
    right:
      - icon: github
        href: https://github.com/philippemichel
      - icon: twitter
        href: https://twitter.com/PhiippeMICHEL
      - icon: mailbox
        text: mail
        href: mailto:philippe.michel@ght-novo.fr
  open-graph:
    locale: fr_FR
format:
    html:
      code-fold: true
      page-layout: full
      highlight-style: ayu
      theme:
        light:
          - sandstone
          - style.scss
        dark: cyborg
      fontsize: 1.2em
editor: source
bibliography: stat.bib
license: "MIT"
echo: false
warning: false
message: false
